# Generated by Django 2.2.4 on 2019-08-14 08:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名前')),
                ('wage', models.IntegerField(blank=True, verbose_name='時給')),
                ('dayOfStart', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('timeOfStart', models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('timeOfEnd', models.DateTimeField(blank=True, null=True, verbose_name='退社時刻')),
                ('timeOfBreak', models.IntegerField(choices=[(0, 0), (15, 15), (30, 30), (45, 45), (60, 60), (75, 75), (90, 90)], default=0, verbose_name='休憩時間')),
                ('workedtime', models.IntegerField(default=0, verbose_name='実働時間')),
                ('approved', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='スタッフ', to='schedule.Staff')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
